### PR TITLE
Update taxonomy V.1.1

### PR DESCRIPTION
**Pull request by PenhleakChan**
13 fixes were made after the taxonomy_en.json file for V.1.1 was
validated on www.jsonlint.com

### CODE REVIEW

**Comment by acorbi** [comment]
@PenhleakChan @DBishton After uploading the current definition of version 1.1 of the taxonomy in English, we have to translate it to the other languages before merging this to the master branch. 

The reason for this is that the master branch should always contain complete and error-free data. 

The resource on Transifex has been updated accordingly, translation can now begin: https://www.transifex.com/projects/p/odm-taxonomy/resource/taxonomy_enjson/
Once translated, we can merge this PR.

Question: Which languages are we going to translate this into? Khmer, Thai, Vietnamese?

**Comment by PenhleakChan** [comment]
We are going to translate them into Khmer, Thai and Vietnamese tomorrow. But we should make preparation for Myanmar and Laos as well, although these two are not immediate priorities.

**Comment by acorbi** [comment]
@PenhleakChan OK! Once it gets translated to a new language, the corresponding translated JSON file can be added to the repo

**Comment by acorbi** [comment]
Branch merged
https://github.com/OpenDevelopmentMekong/odm-localization/tree/update_taxonomy_V.1.1 into master for deploying into data.opendevelopmentmekong.net

**Pull request merged**
